---
title: "Accuracy"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r setup 1, include=FALSE}
library(tidyverse)
library(rio)
library(here)
library(gghighlight)
library(forcats)
library(ggrepel)
library(gt)
library(knitr)
library(kableExtra)
library(reactable)
library(plotly)
library(SCVA)
library(patchwork)
library(colorblindr)
library(scan)

theme_set(theme_minimal(15) +
            theme(legend.position = "bottom",
                  panel.grid.major.x = element_line(color = "gray60"),
                  panel.grid.minor.x = element_blank(),
                  panel.grid.major.y = element_blank())
          )
 
```


## SAJE 

### PND

```{r, include=FALSE}
saje_pnd <- scdf(c(78.26, 70.83, 72.22, 86.09, 86.67, 83.23),
                 phase.design = c(A = 3, B = 3))
```

```{r, include=TRUE}
pnd(saje_pnd, decreasing = FALSE)
```

### Tau-U

#### Parker (2011) Version

```{r, include=TRUE}
saje_1 <- scdf(c(78.26, 70.83, 72.22, 86.09, 86.67, 83.23),
                 phase.design = c(A = 3, B = 3))

saje_res <- tau_u(saje_1)

print(saje_res, complete = TRUE)
```


#### Tarlow (2016) Version

This calculation is based on Kendalls Tau

```{r, include=TRUE}
saje_2 <- scdf(c(A = 78.26, 70.83, 72.22, B = 86.09, 86.67, 83.23))

corrected_tau(saje_2)
```



## LELI

### PND

```{r, include=FALSE}
leli_pnd <- scdf(c(58.82, 61.11, 56.41, 51.85, 56.25, 63.79, 72.34, 71.29),
                 phase.design = c(A = 5, B = 3))
```

```{r, include=TRUE}
pnd(leli_pnd, decreasing = FALSE)
```

### Tau-U

#### Parker (2011) Version

```{r, include=TRUE}
leli_1 <- scdf(c(58.82, 61.11, 56.41, 51.85, 56.25, 63.79, 72.34, 71.29),
                 phase.design = c(A = 5, B = 3))

leli_res <- tau_u(leli_1)

print(leli_res, complete = TRUE)
```


#### Tarlow (2016) Version

This calculation is based on Kendalls Tau

```{r, include=TRUE}
leli_2 <- scdf(c(A = 58.82, 61.11, 56.41, 51.85, 56.25, B = 63.79, 72.34, 71.29))

corrected_tau(leli_2)
```




## GIAD

### PND

```{r, include=FALSE}
giad_pnd <- scdf(c(88.68, 82.93, 87.50, 85.11, 88.10, 85.84, 92.00),
                 phase.design = c(A = 4, B = 3))
```

```{r, include=TRUE}
pnd(giad_pnd, decreasing = FALSE)
```

### Tau-U

#### Parker (2011) Version

```{r, include=TRUE}
giad_1 <- scdf(c(88.68, 82.93, 87.50, 85.11, 88.10, 85.84, 92.00),
                 phase.design = c(A = 4, B = 3))

giad_res <- tau_u(giad_1)

print(giad_res, complete = TRUE)
```


#### Tarlow (2016) Version

This calculation is based on Kendalls Tau

```{r, include=TRUE}
giad_2 <- scdf(c(A = 88.68, 82.93, 87.50, 85.11, B = 88.10, 85.84, 92.00))

corrected_tau(giad_2)
```