---
title: "Tau-U"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: tango
---

## AB Tau-U Calculations with `SCAN` Package

Code for calculations accessible [here](https://jazznbass.github.io/scan-Book/overlapping-indices.html)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r setup 1, include=FALSE}
library(tidyverse)
library(rio)
library(here)
library(gghighlight)
library(forcats)
library(ggrepel)
library(gt)
library(knitr)
library(kableExtra)
library(reactable)
library(plotly)
library(SCVA)
library(patchwork)
library(colorblindr)
library(scan)

theme_set(theme_minimal(15) +
            theme(legend.position = "bottom",
                  panel.grid.major.x = element_line(color = "gray60"),
                  panel.grid.minor.x = element_blank(),
                  panel.grid.major.y = element_blank())
          )
 
```


### SAJE 

#### Parker (2011) Version

```{r, include=TRUE}
saje_1 <- scdf(c(69, 48, 72, 115, 135, 155), 
               phase.design = c(A = 3, B = 3))

saje_res <- tau_u(saje_1)

print(saje_res, complete = TRUE)
```

#### Tarlow (2016) Version

This calculation is based on Kendalls Tau

```{r, include=TRUE}
saje_2 <- scdf(c(A = 69, 48, 72, B = 115, 135, 155))

corrected_tau(saje_2)
```



### LELI

#### Parker (2011) Version

```{r, include=TRUE}
leli_1 <- scdf(c(34, 54, 39, 27, 48, 116, 94, 101), phase.design = c(A = 5, B = 3))

leli_res <- tau_u(leli_1)

print(leli_res, complete = TRUE)
```

#### Tarlow (2016) Version


```{r, include=TRUE}
leli_2 <- scdf(c(A = 34, 54, 39, 27, 48, B = 116, 94, 101))

corrected_tau(leli_2)
```



### GIAD

#### Parker (2011) Version

```{r, include=TRUE}
giad_1 <- scdf(c(159, 123, 72, 94, 210, 226, 275), phase.design = c(A = 4, B = 3))

giad_res <- tau_u(giad_1)

print(giad_res, complete = TRUE)
```

#### Tarlow (2016) Version


```{r, include=TRUE}
giad_2 <- scdf(c(A = 159, 123, 71, 94, B = 210, 226, 275))

corrected_tau(giad_2)
```